const questions = [
  // --- 1-15: Greetings & Introductions (การทักทายและการแนะนำตัว) ---
  { "id": 1, "category": "English Conversation", "question": "A: Hello, my name is Somchai. \nB: _______, Somchai. I'm John.", "options": ["Good luck", "Nice to meet you", "Fine, thank you", "Goodbye"], "answerIndex": 1 },
  { "id": 2, "category": "English Conversation", "question": "A: How are you doing? \nB: _______.", "options": ["I'm a doctor", "I'm doing well", "I'm 20 years old", "I'm from Thailand"], "answerIndex": 1 },
  { "id": 3, "category": "English Conversation", "question": "A: _______ \nB: My name is Mary.", "options": ["Who are you?", "What is your name?", "How do you do?", "Are you Mary?"], "answerIndex": 1 },
  { "id": 4, "category": "English Conversation", "question": "A: How do you do? \nB: _______.", "options": ["I'm fine", "How do you do?", "Thank you", "Nice to see you"], "answerIndex": 1 },
  { "id": 5, "category": "English Conversation", "question": "A: Have a nice day! \nB: _______.", "options": ["You too", "You're welcome", "I'm sorry", "Never mind"], "answerIndex": 0 },
  { "id": 6, "category": "English Conversation", "question": "A: See you later. \nB: _______.", "options": ["You're welcome", "See you", "Not at all", "Yes, please"], "answerIndex": 1 },
  { "id": 7, "category": "English Conversation", "question": "A: Where are you from? \nB: _______.", "options": ["I'm from Bangkok", "I'm 180 cm tall", "I'm a student", "I'm fine"], "answerIndex": 0 },
  { "id": 8, "category": "English Conversation", "question": "A: What do you do? \nB: _______.", "options": ["I'm doing my homework", "I'm a police officer", "I'm fine, thanks", "I'm at home"], "answerIndex": 1 },
  { "id": 9, "category": "English Conversation", "question": "A: Good morning, sir. Can I help you? \nB: _______.", "options": ["Yes, please", "No, I'm not", "Good morning", "I'm sorry"], "answerIndex": 0 },
  { "id": 10, "category": "English Conversation", "question": "A: _______ \nB: It's 10 o'clock.", "options": ["What time is it?", "How much is it?", "How many are there?", "What is the date?"], "answerIndex": 0 },
  { "id": 11, "category": "English Conversation", "question": "A: Excuse me, is this seat taken? \nB: _______, it's free.", "options": ["Yes", "No", "Sorry", "Maybe"], "answerIndex": 1 },
  { "id": 12, "category": "English Conversation", "question": "A: Thank you for your help. \nB: _______.", "options": ["Don't say that", "You're welcome", "Please", "It's okay"], "answerIndex": 1 },
  { "id": 13, "category": "English Conversation", "question": "A: I'm sorry for being late. \nB: _______.", "options": ["Never mind", "You're late", "Don't be sorry", "That's bad"], "answerIndex": 0 },
  { "id": 14, "category": "English Conversation", "question": "A: Could you tell me your phone number? \nB: _______.", "options": ["Yes, it is 081-XXX", "No, I don't have", "I'm Mary", "I'm at work"], "answerIndex": 0 },
  { "id": 15, "category": "English Conversation", "question": "A: Would you like some coffee? \nB: _______, please.", "options": ["Yes", "No", "Sure", "Both 1 and 3"], "answerIndex": 3 },

  // --- 16-30: Asking for & Giving Directions (การถามและบอกทาง) ---
  { "id": 16, "category": "English Conversation", "question": "A: Excuse me, _______ is the police station? \nB: It's next to the bank.", "options": ["what", "where", "when", "who"], "answerIndex": 1 },
  { "id": 17, "category": "English Conversation", "question": "A: How can I get to the bus stop? \nB: _______ straight and turn left.", "options": ["Go", "Run", "Walks", "Going"], "answerIndex": 0 },
  { "id": 18, "category": "English Conversation", "question": "A: Is there a hospital near here? \nB: Yes, _______.", "options": ["it is", "there is", "you are", "this is"], "answerIndex": 1 },
  { "id": 19, "category": "English Conversation", "question": "A: How _______ is it to the airport? \nB: About 5 kilometers.", "options": ["long", "far", "much", "many"], "answerIndex": 1 },
  { "id": 20, "category": "English Conversation", "question": "A: Go past the school, and the park is _______ your right.", "options": ["in", "at", "on", "to"], "answerIndex": 2 },
  { "id": 21, "category": "English Conversation", "question": "A: Excuse me, I'm lost. Can you help me? \nB: _______, where do you want to go?", "options": ["Certainly", "No", "I'm busy", "Go away"], "answerIndex": 0 },
  { "id": 22, "category": "English Conversation", "question": "A: Is it far from here? \nB: No, it's _______ walking distance.", "options": ["in", "at", "within", "far"], "answerIndex": 2 },
  { "id": 23, "category": "English Conversation", "question": "A: Which way is the post office? \nB: It's _______ the street.", "options": ["across", "through", "between", "under"], "answerIndex": 0 },
  { "id": 24, "category": "English Conversation", "question": "A: The bank is _______ the hotel and the pharmacy.", "options": ["next to", "opposite", "between", "among"], "answerIndex": 2 },
  { "id": 25, "category": "English Conversation", "question": "A: Excuse me, where is the nearest ATM? \nB: It's _______ the corner of the street.", "options": ["in", "at", "on", "around"], "answerIndex": 1 },
  { "id": 26, "category": "English Conversation", "question": "A: You need to _______ the bus at the next stop.", "options": ["get off", "get in", "get up", "get out"], "answerIndex": 0 },
  { "id": 27, "category": "English Conversation", "question": "A: Can I walk there? \nB: Yes, it _______ about 10 minutes.", "options": ["takes", "gives", "makes", "goes"], "answerIndex": 0 },
  { "id": 28, "category": "English Conversation", "question": "A: I'm looking for the museum. \nB: Oh, it's _______ the opposite side of the road.", "options": ["on", "at", "in", "by"], "answerIndex": 0 },
  { "id": 29, "category": "English Conversation", "question": "A: Is the market behind the park? \nB: No, it's _______ the park.", "options": ["in front of", "under", "inside", "between"], "answerIndex": 0 },
  { "id": 30, "category": "English Conversation", "question": "A: Thank you for your directions. \nB: _______.", "options": ["No problem", "Never mind", "Not at all", "All of above"], "answerIndex": 3 },

  // --- 31-40: Making Requests & Offering Help (การขอร้องและการเสนอความช่วยเหลือ) ---
  { "id": 31, "category": "English Conversation", "question": "A: _______ you help me with this heavy box? \nB: Of course.", "options": ["May", "Could", "Should", "Shall"], "answerIndex": 1 },
  { "id": 32, "category": "English Conversation", "question": "A: Would you mind _______ the door? \nB: Not at all.", "options": ["close", "closed", "closing", "to close"], "answerIndex": 2 },
  { "id": 33, "category": "English Conversation", "question": "A: May I _______ your pen? \nB: Sure, here it is.", "options": ["borrow", "lend", "keep", "give"], "answerIndex": 0 },
  { "id": 34, "category": "English Conversation", "question": "A: Can I give you a hand? \nB: _______, that's very kind of you.", "options": ["No, thanks", "Yes, please", "I'm busy", "Never mind"], "answerIndex": 1 },
  { "id": 35, "category": "English Conversation", "question": "A: Would you like some help? \nB: No, thank you. I can _______ it.", "options": ["manage", "do", "make", "take"], "answerIndex": 0 },
  { "id": 36, "category": "English Conversation", "question": "A: Could you _______ me a favor? \nB: What is it?", "options": ["make", "do", "get", "give"], "answerIndex": 1 },
  { "id": 37, "category": "English Conversation", "question": "A: Do you want some help with your luggage? \nB: Yes, please. _______.", "options": ["It's very heavy", "I'm fine", "No thanks", "Goodbye"], "answerIndex": 0 },
  { "id": 38, "category": "English Conversation", "question": "A: Is it okay if I smoke here? \nB: No, I'm afraid _______.", "options": ["you are", "it isn't", "you can't", "I don't"], "answerIndex": 2 },
  { "id": 39, "category": "English Conversation", "question": "A: Shall I carry this for you? \nB: That would be _______.", "options": ["great", "bad", "slow", "wrong"], "answerIndex": 0 },
  { "id": 40, "category": "English Conversation", "question": "A: Can you pass me the salt, please? \nB: _______.", "options": ["Here you are", "Thank you", "Yes, it is", "I'm sorry"], "answerIndex": 0 },

  // --- 41-50: Telephone Conversation & Appointments (การคุยโทรศัพท์และการนัดหมาย) ---
  { "id": 41, "category": "English Conversation", "question": "A: Hello, could I speak to Mr. Smith, please? \nB: _______, I'll see if he's in.", "options": ["Hold on", "Hang up", "Call back", "Speak up"], "answerIndex": 0 },
  { "id": 42, "category": "English Conversation", "question": "A: Is Mary there? \nB: Sorry, she's _______ at the moment.", "options": ["out", "in", "here", "on"], "answerIndex": 0 },
  { "id": 43, "category": "English Conversation", "question": "A: Would you like to leave a message? \nB: Yes, please tell her to _______ me back.", "options": ["call", "speak", "talk", "tell"], "answerIndex": 0 },
  { "id": 44, "category": "English Conversation", "question": "A: Who's _______, please? \nB: This is Somchai.", "options": ["speaking", "calling", "talking", "asking"], "answerIndex": 0 },
  { "id": 45, "category": "English Conversation", "question": "A: Are you free this weekend? \nB: Yes, why? \nA: _______ going to the cinema?", "options": ["How about", "What about", "Shall we", "Both 1 and 2"], "answerIndex": 3 },
  { "id": 46, "category": "English Conversation", "question": "A: Let's meet at 5 o'clock. \nB: _______, see you then.", "options": ["I'm busy", "That's fine", "No, thanks", "Maybe"], "answerIndex": 1 },
  { "id": 47, "category": "English Conversation", "question": "A: I'm afraid I can't make it to the meeting. \nB: Oh, that's _______.", "options": ["too bad", "good", "great", "nice"], "answerIndex": 0 },
  { "id": 48, "category": "English Conversation", "question": "A: Can we reschedule our appointment? \nB: Sure, when _______ you?", "options": ["suits", "likes", "meets", "does"], "answerIndex": 0 },
  { "id": 49, "category": "English Conversation", "question": "A: I'll call you again tomorrow. \nB: _______.", "options": ["Goodbye", "Alright", "No problem", "Both 2 and 3"], "answerIndex": 3 },
  { "id": 50, "category": "English Conversation", "question": "A: Thank you for calling. \nB: _______.", "options": ["You're welcome", "Goodbye", "Same to you", "No thanks"], "answerIndex": 1 }
];
